<?php

namespace AlbaBundle\Repository;

/**
 * kaartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class kaartRepository extends \Doctrine\ORM\EntityRepository
{
}
