alba_kamer_prijs:
    resource: "@AlbaBundle/Controller/KamerPrijsController.php"
    type:     annotation

alba_reservering:
    resource: "@AlbaBundle/Controller/ReserveringController.php"
    type:     annotation

alba_seizoen:
    resource: "@AlbaBundle/Controller/SeizoenController.php"
    type:     annotation

alba_kamer:
    resource: "@AlbaBundle/Controller/KamerController.php"
    type:     annotation

alba_reservering:
    resource: "@AlbaBundle/Controller/ReserveringController.php"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

alba:
    resource: "@AlbaBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
