alba_kamer_afbeelding:
    resource: "@AlbaBundle/Controller/KamerAfbeeldingController.php"
    type: annotation

alba_klant:
    resource: "@AlbaBundle/Controller/KlantController.php"
    type:     annotation

alba_reservering:
    resource: "@AlbaBundle/Controller/ReserveringController.php"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

alba:
    resource: "@AlbaBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

<<<<<<< HEAD
=======
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

adesigns_calendar:
  resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"
>>>>>>> fb2e722c37dc7607dafb49f8df1eda6f9516d573
