alba_betaling:
    resource: "@AlbaBundle/Controller/BetalingController.php"
    type:     annotation

alba_kaart:
    resource: "@AlbaBundle/Controller/KaartController.php"
    type:     annotation

alba_betaling:
    resource: "@AlbaBundle/Controller/BetalingController.php"
    type:     annotation

alba_extra:
    resource: "@AlbaBundle/Controller/ExtraController.php"
    type: annotation

alba_kamer_afbeelding:
    resource: "@AlbaBundle/Controller/KamerAfbeeldingController.php"
    type: annotation

alba_klant:
    resource: "@AlbaBundle/Controller/KlantController.php"
    type:     annotation

alba_gast:
    resource: "@AlbaBundle/Controller/GastController.php"
    type:     annotation

alba_bank:
    resource: "@AlbaBundle/Controller/BankController.php"
    type:     annotation

alba_reservering:
    resource: "@AlbaBundle/Controller/ReserveringController.php"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

alba:
    resource: "@AlbaBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

adesigns_calendar:
  resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"
