<?php

namespace AlbaBundle\Repository\Kamer;

/**
 * PrijsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrijsRepository extends \Doctrine\ORM\EntityRepository
{
}
