<?php

namespace AlbaBundle\Repository;

/**
 * AlbaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbaRepository extends \Doctrine\ORM\EntityRepository
{
}
