<?php

namespace AlbaBundle\Repository;

/**
 * BetalingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BetalingRepository extends \Doctrine\ORM\EntityRepository
{
}
