<?php

namespace AlbaBundle\Repository;

/**
 * GastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GastRepository extends \Doctrine\ORM\EntityRepository
{
}
