<?php

namespace AlbaBundle\Repository;

/**
 * KaartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KaartRepository extends \Doctrine\ORM\EntityRepository
{
}
