<?php

namespace AlbaBundle\Repository;

/**
 * Kamer_PrijsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Kamer_PrijsRepository extends \Doctrine\ORM\EntityRepository
{
}
