<?php

namespace AlbaBundle\Repository;

/**
 * KamerAfbeeldingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamerAfbeeldingRepository extends \Doctrine\ORM\EntityRepository
{
}
