<?php

namespace AlbaBundle\Repository;

/**
 * KamerPrijsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KamerPrijsRepository extends \Doctrine\ORM\EntityRepository
{
}
