<?php

namespace AlbaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReserveringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReserveringRepository extends EntityRepository
{
    public function findCustomer(){

    }
}
