<?php

namespace AlbaBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * ReserveringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReserveringRepository extends EntityRepository
{
    public function CustomerShow($klantId){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->from('AlbaBundle:Klant', 'k')
            ->select(array('k.id','k.voornaam', 'k.tussenvoegsel', 'k.achternaam'))
            ->where('k.id = :klantId')
            ->setParameter('klantId', $klantId);

             return $qb->getQuery()->getResult();
    }
}
