<?php

namespace AlbaBundle\Repository;

/**
 * SeizoenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeizoenRepository extends \Doctrine\ORM\EntityRepository
{
}
